language: java
jdk:
- oraclejdk8
before_install:
- chmod +x ./gradlew
script:
- 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then bash ./gradlew check; fi'
- 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then bash ./gradlew test integrationTest; fi'
- "./gradlew sendCoverageToCodacy"
deploy:
- provider: releases
  api_key:
    secure: ltLzm1VWcBj5sLTqtEUQyd3JG5pYZ6nQG5czsWB28hvJ3wkVa6vt7L5j3OS8wZuaIdE6eDJ2rMfQ5qS1FAE91SiQfCsMArsZ5C2cWm7BSz70MAa2zCWgxxlMsvARTnSLaP9mVgbZN0js2p0ETVVuUj+MG1dQJGXhsggmFI3ZSxCnWpoAhtGDVvQr8BZp4w5hPJ0Xm144v9ZnT2oUwmwevlVFzO+QzjiUJwPCjy4y6rJAJDdYdY0mTUQq7Y9SwkjXQACNwDRs6ITQ4nbClCk7RtDIKUFYWvuq9IRD0OhVXibTtMC4yocl+PsM6XvCYCAWPjLon20Pc2fdepzWhYPkyoOf9SDDUFAHEjYQ+vw2BkQpx3WwMZDLJbGXI1z0+evYUhSxr7oRSzoRfpCYFtEJ7toLb8SPTsYkyQQp5N1EDNtnIgBZhsQpFdxDgZ8vrVeWiLVtzX5ARgz0GV/yL2v+2ZzPg7usEJSNC6xwyjGiPGDtggUy2HIsP1ohl56VVvU5RjfoKcXxysbm0L43sddZHIuNggyku7pNlYsgHdrUf/0qanxxrU46w8M4vUdyd1oC/pXwaUkpdjA6nFU+ouoX1ScihxZzlkE2TYEFJqbKcWQ8d9zeYW90pemc8oWZJcylyF0ef2MJKy3DgNplnoSJM6q6sDunAA5wGN5A+vu/Ahw=
  skip_cleanup: true
  file_glob: true
  file: "./build/libs/*"
  on:
    repo: Sybit-Education/airtable.java
    tags: true
- provider: script
  skip_cleanup: true
  script: "./gradlew -i bintrayUpload"
  on:
    repo: Sybit-Education/airtable.java
    tags: true
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories: "â€” $HOME/.gradle"
